name: example for hrdwdmrbl
on:
  push:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: git diff-tree -r origin/master..HEAD --name-only --no-commit-id --diff-filter=MA
