name: example for hrdwdmrbl
on:
  push:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: git log
      - run: git diff HEAD~10
